version: '3.8'

networks:
  thunderstruck-net:
    driver: bridge

services:
  # --- DATABASE ---
  oracle:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-thunderstruck
    ports:
      - "1521:1521"
    environment:
      ORACLE_PWD: password
    networks:
      - thunderstruck-net

  # --- KAFKA & DEBEZIUM ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - thunderstruck-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - thunderstruck-net

  debezium:
    # Mudamos para o repositório quay.io que tem a tag nightly atualizada
    image: quay.io/debezium/connect:nightly
    container_name: thunderstruck-infra-debezium-1
    depends_on:
      - kafka
      - oracle
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_REPLICATION_FACTOR: 1
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_PLUGIN_PATH: /kafka/connect
    networks:
      - thunderstruck-net
    volumes:
      # MANTENHA O DRIVER! Ele ainda é necessário
      - ./drivers/ojdbc11.jar:/kafka/libs/ojdbc11.jar
      - ./drivers/ojdbc11.jar:/kafka/connect/debezium-connector-oracle/ojdbc11.jar
      
  # --- CAMUNDA 8 FULL STACK ---
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - thunderstruck-net

  zeebe:
    image: camunda/zeebe:8.4.0
    environment:
      - ZEEBE_LOG_LEVEL=debug
      # --- ESSAS 3 LINHAS ESTAVAM FALTANDO ---
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME=io.camunda.zeebe.exporter.ElasticsearchExporter
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL=http://elasticsearch:9200
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_INDEX_PREFIX=zeebe-record
    depends_on:
      - elasticsearch
    ports:
      - "26500:26500"
    networks:
      - thunderstruck-net

  operate:
    image: camunda/operate:8.4.0
    ports:
      - "8081:8080"
    environment:
      - CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_OPERATE_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - zeebe
      - elasticsearch
    networks:
      - thunderstruck-net

  tasklist:
    image: camunda/tasklist:8.4.0
    ports:
      - "8082:8080"
    environment:
      - CAMUNDA_TASKLIST_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_TASKLIST_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_TASKLIST_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - zeebe
      - elasticsearch
    networks:
      - thunderstruck-net

  optimize:
    image: camunda/optimize:8.4.0
    ports:
      - "8084:8080"
    environment:
      - CAMUNDA_OPTIMIZE_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_OPTIMIZE_ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - zeebe
      - elasticsearch
    networks:
      - thunderstruck-net